### ISSUE TITLE
Back Button - No Pages Exception

### ISSUE THREAD

**Issue by LanceMcCarthy** [dotMorten/Xamarin.Forms.UWPShell.Sample#2]
When using the back button, if there are no pages in _navModel.Roots, an exception is thrown.

**Problem**
In `Xamarin.Forms.Platform.UWP.Platform`, line 257 checks for the latest page in the stack with `Last()`. 

https://github.com/dotMorten/Xamarin.Forms/blob/cced5716266b317a1b2e4e53254a64da6551ca8f/Xamarin.Forms.Platform.UAP/Platform.cs#L257

**Steps to Reproduce**
1. Run the Default Shell Template example (UWP)
2. Click the Back button

**Suggestion**
My suggestion is to use `LastOrDefault()` and check for null.

![image](https://user-images.githubusercontent.com/3520532/56456854-261cf700-6340-11e9-9c89-874bdb10662f.png)

**Comment by LanceMcCarthy** [comment]
This seems to have resolved it 

```csharp
internal bool BackButtonPressed()
{
	Page lastRoot = _navModel?.Roots?.LastOrDefault();

	if(lastRoot != null)
	{
		bool handled = lastRoot.SendBackButtonPressed();

		if (!handled && _navModel.Tree.Count > 1)
		{
			Page removed = _navModel.PopModal();

			if (removed != null)
			{
				SetCurrent(_navModel.CurrentPage, true);
				handled = true;
			}
		}

		return handled;
	}

	return false;
}
```

Note: I tried to commit this change and submit it as a PR, but for some reason my cloned submodule has your latest changes as uncommited staged changes. I'm confused as to why this is happening and rather not make a  further mess out of it.

**Comment by dotMorten** [comment]
Duplicate: https://github.com/xamarin/Xamarin.Forms/pull/5933
